---
# tasks file for sample-apache
-  name: start and enable httpd
   service:
       name:  httpd
       state:  started
       enabled:  yes
-  name: enable and start firewalld
   service: 
       name:  firewalld
       state:  started
       enabled:  yes
-  name: open http on firewall
   firewalld:
       service:  http
       state: enabled
       permanent:  yes
       immediate:  yes
-  name: copy index file
   template: 
       src:  templates/index.html.j2
       dest: /var/www/html/index.html
   notify:
      - restart httpd 
